name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Restore vcpkg cache
        uses: actions/cache@v4
        with:
          path: |
            vcpkg
            build/vcpkg_installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
      - name: Install toolchain
        run: sudo apt-get update && sudo apt-get install -y clang-16 ninja-build cmake
      - name: Bootstrap vcpkg
        run: |
          [[ -d vcpkg ]] || git clone https://github.com/microsoft/vcpkg.git vcpkg
          ./vcpkg/bootstrap-vcpkg.sh
      - name: Configure & Build
        run: |
          cmake -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
          cmake --build build --parallel $(nproc)
      - name: Build & Test mini-stl
        run: |
          cmake -S mini-stl -B mini-stl/build -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build mini-stl/build --parallel
          cd mini-stl/build
          ctest --output-on-failure --output-junit test_result.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mini-stl-test-report
          path: mini-stl/build/test_result.xml