name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Restore vcpkg cache
        uses: actions/cache@v4
        with:
          path: |
            vcpkg
            build/vcpkg_installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
      - name: Install toolchain
        run: sudo apt-get update && sudo apt-get install -y clang-16 ninja-build cmake
      - name: Bootstrap vcpkg
        run: |
          [[ -d vcpkg ]] || git clone https://github.com/microsoft/vcpkg.git vcpkg
          ./vcpkg/bootstrap-vcpkg.sh
      - name: Configure & Build
        run: |
          cmake -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
          cmake --build build --parallel $(nproc)
      - name: Test
        run: ctest --test-dir build --output-junit test_result.xml
      - name: Upload Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test-Report
          path: build/test_result.xml
          reporter: jest-junit