name: Deploy Blog to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出 main 分支代码
      - name: Checkout main
        uses: actions/checkout@v4

      # 2. 自动创建 gh-pages 分支（如果不存在）
      - name: Create gh-pages branch if not exists
        run: |
          git fetch origin gh-pages 2>/dev/null || git checkout -b gh-pages
          git push -u origin gh-pages || true

      # 3. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/blog  # 替换为你的博客目录
          publish_branch: gh-pages   # 确保分支名称正确
          commit_message: "Auto deploy blog content"