# .github/workflows/deploy-blog.yml
name: Deploy Blog to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read      # 仅需读取主分支代码
  pages: write        # GitHub Pages 部署权限
  id-token: write     # 用于生成JWT签名

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 配置 Pages 环境
      - name: Configure Pages
        uses: actions/configure-pages@v4

      # 3. 上传博客目录为 Pages artifact
      - name: Upload blog directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/blog  # 确保路径与实际博客目录一致
          # 可选：排除不需要的文件
          # exclude: |
          #   *.tmp
          #   **/private/

      # 4. 部署到 GitHub Pages
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4